apiVersion: v1
kind: PersistentVolume
metadata:
  name: myfirstpv
  namespace: kubeteach
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/volume/nginx"
  claimRef:
    name: myfirstpvc
    namespace: kubeteach
