apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim-a-lot
  namespace: kubeteach-pv-troubleshoot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
