{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeteach.name" . }}
  labels:
    {{- include "kubeteach.labels" . | nindent 4 }}
spec:
  ports:
  - name: metrics
    port:  {{ .Values.service.port }}
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "kubeteach.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
{{- end}}