{{- if .Values.webterminal.credentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeteach.name" . }}-webterminal
  labels:
    {{- include "kubeteach.labels" . | nindent 4 }}
stringData:
  credentials: {{ include "kubeteach.webterminalCredentials" . }}
{{- end}}
