apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeteach.webterminalServiceAccountName" . }}
  labels:
    {{- include "kubeteach.labels" . | nindent 4 }}
  {{- with .Values.webterminal.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
