---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: kubeteach-pv-troubleshoot
spec: {}
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim-a-lot
  namespace: kubeteach-pv-troubleshoot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-has-to-less
  namespace: kubeteach-pv-troubleshoot
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/opt/volume/nginx"
  claimRef:
    name: pvc-claim-a-lot
    namespace: kubeteach-pv-troubleshoot
