# kubeteach helm settings can be done under kubeteach, for possible values see kubeteach-core helm chart
kubeteach:
  replicaCount: 1

  images:
    kubeteach:
      repository: ghcr.io/dergeberl/kubeteach
      pullPolicy: Always
      # tag: "latest"
    kubeteachWebterminal:
      repository: ghcr.io/dergeberl/kubeteach-webterminal
      pullPolicy: Always
      # tag: "latest"

  dashboard:
    enabled: false
    service:
      type: ClusterIP
      port: 80
    credentials:
      username: "kubeteach"
      # password: "password" # if not set a random string will be created if secret does not exists

  webterminal:
    enabled: false
    service:
      type: ClusterIP
      port: 8080
    credentials:
      username: "terminal"
      # password: "password" # if not set a random string will be created if secret does not exists
    serviceAccount:
      annotations: { }
      clusterAdmin: true

  service:
    enabled: false
    type: ClusterIP
    port: 8080

  imagePullSecrets: [ ]
  nameOverride: ""

  serviceAccount:
    name: kubeteach-sa
    annotations: { }

  podAnnotations: { }

  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

  nodeSelector: { }

  tolerations: [ ]

  affinity: { }
